const message = {
    login: {
        email_required: 'メールアドレスを入力してください',
        email_invalid: 'メールアドレスを正しく入力してください',
        password_required: 'パスワードを入力してください',
    },
    requirement:'この項目は必須入力です',
    requirement_select:'この項目は選んでください',
    zenkaku_kana: '全角カナを入力してください',
    name_alpha: 'アルファベットを入力してください',
    zipcode_regex: '正しい郵便番号を入力してください(例:123-4567)',
    address_regex: '正しい住所を入力してください',
    phone_regex: '正しい電話番号を入力してください(例:080-4567-9091)',
    email_required: 'メールアドレスを入力してください',
    email_invalid: 'メールアドレスを正しく入力してください',
    default_error: 'エラーが発生しました。もう一度やり直してください。',
    cookies_expired: 'ログインセッションの有効期限が切れました。再度ログインしてください',
    error_500: 'エラーが発生しました。もう一度やり直してください',
    error_403: '権限がないか、このページにアクセスできません',
    error_405: '許可されていないメソッド',
    error_404: 'データなし',
    error_400: '無効なリクエスト',
    error_401: 'メールアドレスまたはパスワードに誤りがあります',
    error_429: 'エラーがリクエスト制限を超えました',
    error_422: '入力されたフォームが正確でないか、必須項目が入力されていません',
    error_network: 'エラーネットワーク',
    error_unknown: '不明なエラーが発生しました、もう一度お試しください',
    error_session_expires:'セッションの有効期限が切れました。再度ログインしてください',
    tour_id_note:'満席の場合、キャンセル待ち受付になります。',
    password_note:'次回以降の参加申込み時に利用します',
    being_in_note:'ご家族に在園卒園のご兄姉はいらっしゃいますか。ご不在の場合は「初めての入園」をお選びください。',
    other_kindy_note:'他に見学予定または見学済みの園があれば教えてください。',
    choice_reason:'Beyondia International School やまた幼稚園を希望する動機、園探しの上で大切にしているポイントなどがあればお聞かせください。',
}

export default message;